const productData = [
    {
      id: 1,
      category: "Clothing",
      title: "Men's Casual Shirt",
      rating: 4.2,
      price: 25.99,
      description: "Comfortable and stylish casual shirt for everyday wear.",
    },
    {
      id: 2,
      category: "Clothing",
      title: "Women's Summer Dress",
      rating: 4.5,
      price: 35.49,
      description: "Lightweight and breezy dress perfect for summer days.",
    },
    {
      id: 3,
      category: "Electronics",
      title: "Wireless Bluetooth Headphones",
      rating: 4.8,
      price: 59.99,
      description: "High-quality sound with noise-cancellation features.",
    },
    {
      id: 4,
      category: "Electronics",
      title: "Smartphone with 128GB Storage",
      rating: 4.6,
      price: 499.99,
      description: "Fast performance and ample storage for all your needs.",
    },
    {
      id: 5,
      category: "Home Appliances",
      title: "Microwave Oven",
      rating: 4.1,
      price: 89.99,
      description: "Compact and efficient oven for quick meal preparation.",
    },
    {
      id: 6,
      category: "Home Appliances",
      title: "Vacuum Cleaner",
      rating: 3.9,
      price: 120.49,
      description: "Powerful suction for a cleaner and healthier home.",
    },
    {
      id: 7,
      category: "Books",
      title: "Learn JavaScript in 30 Days",
      rating: 4.7,
      price: 15.99,
      description: "A beginner-friendly guide to mastering JavaScript.",
    },
    {
      id: 8,
      category: "Books",
      title: "Mastering React Development",
      rating: 4.9,
      price: 19.49,
      description: "Advanced techniques for building React applications.",
    },
    {
      id: 9,
      category: "Sports",
      title: "Cricket Bat - Professional Edition",
      rating: 4.3,
      price: 99.99,
      description: "Durable and lightweight bat for powerful shots.",
    },
    {
      id: 10,
      category: "Sports",
      title: "Yoga Mat - Non-Slip",
      rating: 4.5,
      price: 29.99,
      description: "Comfortable and slip-resistant mat for yoga practice.",
    },
  ];
  
  export { productData };
  